<?php
namespace Walker\PriceRange\Block;

use \Magento\Framework\View\Element\Template;
use \Magento\Framework\View\Element\Template\Context;

class Index extends Template{

    public function __construct(Context $context, \Magento\Store\Model\StoreManagerInterface $storeManager)
    {
        $this->_storeManager = $storeManager;
        parent::__construct($context);
    }

    public function getBaseUrl()
    {
        return parent::getBaseUrl(); // TODO: Change the autogenerated stub
    }

    public function getLowRangeData(){
        return $this->getLowRange();
    }

    public function getHighRangeData(){
        return $this->getHighRange();
    }
}
