<?php declare(strict_types=1);
    /** @var \Magento\Framework\View\Element\Template $block */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>
        }
    }
</script>

<div data-bind="scope: 'component-a'">
    <h3 data-bind="text: label"></h3>
    <div data-bind="text: amount"></div>
</div>

<div data-bind="scope: 'component-b'">
    <h3 data-bind="text: title"></h3>
    <div data-bind="text: value"></div>
</div>
